export const SET_SUBSCRIBER = "SET_SUBSCRIBER";
export const DELETE_SUBSCRIBER = "DELETE_SUBSCRIBER";
export const SELECT_SUBSCRIBER = "SELECT_SUBSCRIBER";
export const UPDATE_SUBSCRIBER = "UPDATE_SUBSCRIBER";
